### ISSUE TITLE
Add Authentication with credentials and rights

### ISSUE THREAD

**Issue by orenault** [nestor-qa/nestor#42]
Is it possible to add Authentication and rights management ?

Maybe as it's done in Jenkins, with a matrix of rights/users.
And the ability to connect to a ldap.

This should be disable by default (everybody can do anything... create, delete...).

Thanks
Olivier

**Comment by kinow** [comment]
Users table created, populated with examples, tested. API providing right methods for adding, logging in, logging out, and editing users.

Will leave the issue open to discuss and implement the permissions, groups or other schema for deciding which users have permissions to what parts of the system.

**Comment by kinow** [comment]
Good package for Laravel https://github.com/spatie/laravel-permission

**Comment by kinow** [comment]
Laravel Gates and Policies also look promising https://laravel.com/docs/5.3/authorization

**Comment by kinow** [comment]
spatie/laravel-permission seems a bit more complete. Using Gates and Policies, we'd have to write most of the logic around a permission/role framework - basically rewriting laravel-permission.

Going with laravel-permission then. Just need to add the package to our dependencies, and then start creating views for administration. Plus a default admin and a default user users.

**Comment by kinow** [comment]
- [ x ] Choose a library
- [ x ] Install library
- [ ] Choose roles
- [ ] Create default roles in seeds 
- [ ] Add role-checking code in the backend
- [ ] Create UI check functions (Backbone model, sending an ajax request to the backend to ask, kinda like hasRoles blade annotation from laravel-permission)
- [ ] Update UI to check permissions
- [ ] Add Administration to the menu, but only to Administrator users (or that hasRole('admin'))
- [ ] Create views for administration section
- [ ] Write documentation, updating Getting Started, but also writing two new sections, one for developers, and one for users
- [ ] Write tests (unit and/or functional)
- [ ] Have a beer or two

**Comment by kinow** [comment]
Hmmm, thinking well, https://github.com/Zizaco/entrust seems to have a few more features, and have more users too. Besides, just found a good tutorial for JWT and Entrust (https://scotch.io/tutorials/role-based-authentication-in-laravel-with-jwt)

**Comment by kinow** [comment]
Hmmm, bitten by https://github.com/Zizaco/entrust/issues/460

**Comment by kinow** [comment]
Luckily the workaround provided there works for us too. Now bitten by https://github.com/Zizaco/entrust/issues/468, ugh

**Comment by kinow** [comment]
TestLink has the following roles:

* 1 - reserved system role 1
* 2 - reserved system role 2
* 3 - no rights
* 4 - test designer
* 5 - guest
* 6 - senior tester
* 7 - tester
* 8 - admin
* 9 - leader

**Comment by kinow** [comment]
TestRail "comes with a few preconfigured useful roles such as Guest, Tester or Lead." (http://docs.gurock.com/testrail-userguide/howto-permissions)

**Comment by kinow** [comment]
I think we could go with something like:

* admin (can do anything)
* guest (can only access the system, and view specific reports and dashboards)
* tester (can only create new test runs, and execute them)
* test designer (tester + can also access specification, and planning)
* lead (tester + can assign test cases)
* lead (tester +
